// The ACTOR overlays' own static initialisers.
//
// ov002 is the engine overlay and ov009 is the level's; everything else the
// castle grounds names lives in an overlay that exists for a handful of actor
// classes several levels share. Those are mounted per symbol (ovdata.py
// --pack, one ovNNN_syms.txt each) and their sinits run here, exactly where
// the DS runs them: after the mount, before the first spawn.
//
// Nothing in this file is behaviour. Every __sinit_ovNNN_* is matched src --
// the SharedFilePtr constructions and the small static tables an actor's
// InitResources loads through -- and the port's only job is to call them in
// ROM order and to check the mount underneath them first.
#include <cstdio>
#include <cstdlib>

extern "C" {

/* generated by port/tools/ovdata.py --pack: asserts every mounted symbol's
   packed offset against the ROM's own spacing, then rebases the internal
   pointers onto host storage */
void port_ov085_pack_check(void);
void port_ov085_syms_patch(void);

/* ov085: RABBIT, LAKITU_BRO (and the four classes other levels name) */
void __sinit_ov085_0212f2a8(void);
void __sinit_ov085_0212f3a0(void);
void __sinit_ov085_0212f5ec(void);
void __sinit_ov085_0212f9bc(void);
void __sinit_ov085_0212fa40(void);
void __sinit_ov085_0212fdb0(void);

/* ---- the RABBIT's eight states -------------------------------------------
   __sinit_ov085_0212f5ec builds eight State objects at ov085
   0x0213066c..0x021306dc out of sixteen {function, delta} statics at
   0x0213003c..0x021300b4, and Rabbit::Behavior dispatches the second half of
   whichever one is at +0x364 every frame. Those statics are the ROM's own
   words -- DS code addresses -- so the host bodies are seated over them
   before the sinit copies them, the LakituBro treatment
   (port/unmatched/LakituBro_Behavior.cpp) for a class whose Behavior needs no
   host copy at all: the matched source reads the pair as two plain ints and
   does the delta arithmetic itself, so MSVC's PMF representation never comes
   into it. */
struct PortPmf { unsigned fn; int delta; };
extern PortPmf data_ov085_0213003c[], data_ov085_02130044[],
    data_ov085_0213004c[], data_ov085_02130054[], data_ov085_0213005c[],
    data_ov085_02130064[], data_ov085_0213006c[], data_ov085_02130074[],
    data_ov085_0213007c[], data_ov085_02130084[], data_ov085_0213008c[],
    data_ov085_02130094[], data_ov085_0213009c[], data_ov085_021300a4[],
    data_ov085_021300ac[], data_ov085_021300b4[];

void func_ov085_0212a904(void *); void func_ov085_0212aaa4(void *);
void func_ov085_0212aaec(void *); void func_ov085_0212ac3c(void *);
void func_ov085_0212ac4c(void *); void func_ov085_0212ad8c(void *);
void func_ov085_0212ae08(void *); void func_ov085_0212b3fc(void *);
void func_ov085_0212b444(void *); void func_ov085_0212b478(void *);
void func_ov085_0212b4b4(void *); void func_ov085_0212b75c(void *);
void func_ov085_0212b86c(void *); void func_ov085_0212b8a0(void *);
void func_ov085_0212bc14(void *);

/* LakituBro's twenty-two {function, delta} statics carry DS code addresses,
   and __sinit_ov085_0212fa40 copies them into his eleven State objects. Seat
   the host bodies over the SOURCE side, before the copy, so the sinit
   propagates host addresses wherever the ROM propagates DS ones.
   port/unmatched/LakituBro_Behavior.cpp */
void port_lakitu_bro_states_seat(void);

/* ov098: CANNON (and the crate, the water bomb and the two arrow signs) */
void port_ov098_pack_check(void);
void port_ov098_syms_patch(void);
void __sinit_ov098_0213bf9c(void);
void __sinit_ov098_0213c058(void);
void __sinit_ov098_0213c214(void);
void __sinit_ov098_0213c2b4(void);

/* the cannon's four {function, delta} statics, seated the same way as the
   Lakitu's -- port/unmatched/Cannon_Behavior.cpp */
void port_cannon_states_seat(void);

/* ov089: NO CLASS OF ITS OWN IS REGISTERED. The castle grounds' front-door
   pair asks LoadKeyModels for a key model, and that walks two arrays of
   SharedFilePtr pointers in ov089's bss which only ov089's own sinit builds.
   Mounted for its data, the way an overlay mount is meant to work. */
void port_ov089_pack_check(void);
void port_ov089_syms_patch(void);
void __sinit_ov089_021328d4(void);
extern unsigned char data_ov089_02132894[], data_ov089_021328b4[];
extern unsigned char data_ov085_021305d8[];
extern unsigned char data_ov002_0211094c[], data_ov002_0210da40[],
    data_ov002_0210d9a0[], data_ov002_0210d9c0[];

/* ov100: BUTTERFLY, FISH, DOOR (and the chomp, the iron ball, the star door
   and the path lift, which other levels name) */
void port_ov100_pack_check(void);
void port_ov100_syms_patch(void);
void __sinit_ov100_021473bc(void);
void __sinit_ov100_021474e8(void);
void __sinit_ov100_021475a4(void);
void __sinit_ov100_02147698(void);
void __sinit_ov100_02147a70(void);
void __sinit_ov100_02147bc0(void);
void __sinit_ov100_02147d7c(void);

/* ov102: QUESTION_BLOCK (and the bob-omb, the koopa shell, the warp pipe and
   the rest of the level-furniture set other levels name). Its CODE has been
   compiled since gate 19 -- the cannon's link closure reached two of its
   functions -- but its DATA is mounted here for the first time. */
void port_ov102_pack_check(void);
void port_ov102_syms_patch(void);
void __sinit_ov102_0214d714(void);
void __sinit_ov102_0214d908(void);
void __sinit_ov102_0214de70(void);
void __sinit_ov102_0214dfac(void);

/* the fish's seven {function, delta} statics, seated the same way -- its own
   Behavior is a host copy for the PMF reason, so both live in
   port/unmatched/Fish_Behavior.cpp */
void port_fish_states_seat(void);

/* the door's fifteen, likewise. __sinit_ov100_02147698 copies them into nine
   callback nodes, two pairs per node; the door dispatches word 0 when it
   seats a node and word 8 every frame -- port/unmatched/Door_Behavior.cpp */
void port_door_callbacks_seat(void);

/* the question block's six, likewise -- three states of two halves each, one
   of which has no C at all. port/unmatched/QuestionBlock_States.cpp */
void port_question_block_states_seat(void);

/* ---- the BUTTERFLY's eight states ----------------------------------------
   __sinit_ov100_021473bc copies eight {function, delta} statics from ov100
   0x02147e20..0x02147e58 into data_ov100_02148628, and Butterfly::Behavior
   dispatches one of them every frame. Those statics are the ROM's own words
   -- DS code addresses -- so the host bodies are seated over them before the
   sinit copies them.

   The BUTTERFLY NEEDS NO HOST COPY of its Behavior, the rabbit's case rather
   than the fish's: its matched source already reads the pair as two plain
   ints and does the virtual-bit and this-adjustment arithmetic itself
   (`if (p & 1) f = **(...); else f = m->fn;`), so MSVC's pointer-to-member
   representation never comes into it. All eight deltas are zero in the ROM,
   which is what the check below asserts. */
struct PortPmf2 { unsigned fn; int delta; };
extern PortPmf2 data_ov100_02147e20[], data_ov100_02147e28[],
    data_ov100_02147e30[], data_ov100_02147e38[], data_ov100_02147e40[],
    data_ov100_02147e48[], data_ov100_02147e50[], data_ov100_02147e58[];

void func_ov100_0214109c(void *); void func_ov100_0214117c(void *);
void func_ov100_021412d8(void *); void func_ov100_02140e44(void *);
void func_ov100_02141470(void *); void func_ov100_021415bc(void *);
void func_ov100_02141800(void *); void func_ov100_02141848(void *);

}  /* extern "C" */

static const struct { PortPmf2 *slot; unsigned rom; void (*host)(void *); }
g_butterfly_states[] = {
    {data_ov100_02147e20, 0x0214117c, func_ov100_0214117c},
    {data_ov100_02147e28, 0x02141470, func_ov100_02141470},
    {data_ov100_02147e30, 0x021412d8, func_ov100_021412d8},
    {data_ov100_02147e38, 0x02140e44, func_ov100_02140e44},
    {data_ov100_02147e40, 0x02141800, func_ov100_02141800},
    {data_ov100_02147e48, 0x02141848, func_ov100_02141848},
    {data_ov100_02147e50, 0x021415bc, func_ov100_021415bc},
    {data_ov100_02147e58, 0x0214109c, func_ov100_0214109c},
};

/* ---- ov089's key-model tables POINT OUT OF ov089 --------------------------
   LoadKeyModels indexes two arrays of SharedFilePtr POINTERS at ov089
   0x02132894 and 0x021328b4 -- one pair per playable character -- and they do
   not all point at ov089. Six of the sixteen cross into other overlays:
   character 5's model lives in ov085's bss and four more in ov002's data.

   ovdata.py's rebase is PER OVERLAY by construction: it rewrites a word only
   when the target lands inside a symbol that same generator run emitted, so a
   pointer from ov089 into ov085 is left as the DS address it was -- correctly,
   because guessing across a mount boundary is exactly what that rule exists to
   prevent. This is the seam that closes those six by hand, and it closes them
   the way every seat in this file does: each word is checked against the ROM
   address it is supposed to hold before it is rewritten, so a mount that has
   drifted says so instead of being papered over.

   The castle grounds needs one of the six. Its front-door pair carries key
   index 5, whose model is the ov085 one; the walk found it by faulting in
   SharedFilePtr::LoadFile on a null `this` when the port still faked these
   two arrays with zeros. */
static const struct { unsigned char *tbl; unsigned off; unsigned rom;
                      unsigned char *host; }
g_ov089_keymodels[] = {
    {data_ov089_02132894, 0x14, 0x021305d8, data_ov085_021305d8},
    {data_ov089_02132894, 0x18, 0x021305d8, data_ov085_021305d8},
    {data_ov089_02132894, 0x1c, 0x0211094c, data_ov002_0211094c},
    {data_ov089_021328b4, 0x08, 0x0210da40, data_ov002_0210da40},
    {data_ov089_021328b4, 0x0c, 0x0210d9a0, data_ov002_0210d9a0},
    {data_ov089_021328b4, 0x10, 0x0210d9c0, data_ov002_0210d9c0},
};

static void port_ov089_keymodels_fixup(void)
{
    for (unsigned i = 0;
         i < sizeof g_ov089_keymodels / sizeof g_ov089_keymodels[0]; ++i) {
        unsigned *w = (unsigned *)(g_ov089_keymodels[i].tbl +
                                   g_ov089_keymodels[i].off);
        if (*w != g_ov089_keymodels[i].rom) {
            std::fprintf(stderr, "FATAL: ov089 key model %u: the mount holds "
                         "%08x, the ROM's own table says %08x -- WRONG BYTES\n",
                         i, *w, g_ov089_keymodels[i].rom);
            std::abort();
        }
        *w = (unsigned)(size_t)g_ov089_keymodels[i].host;
    }
}

static void port_butterfly_states_seat(void)
{
    for (unsigned i = 0;
         i < sizeof g_butterfly_states / sizeof g_butterfly_states[0]; ++i) {
        PortPmf2 *p = g_butterfly_states[i].slot;
        if (p->fn != g_butterfly_states[i].rom || p->delta != 0) {
            std::fprintf(stderr, "FATAL: Butterfly state %u: the mount holds "
                         "%08x/%d, the ROM's own table says %08x/0 -- WRONG "
                         "BYTES\n", i, p->fn, p->delta,
                         g_butterfly_states[i].rom);
            std::abort();
        }
        p->fn = (unsigned)(size_t)g_butterfly_states[i].host;
    }
}

/* ov085 0x0212b8dc IS NOT HOSTED, and it is the one hole in the rabbit. It is
   the Main half of state 0x021306cc -- the state Rabbit::InitResources itself
   enters on its own last line -- so it is what an ACTIVE rabbit runs every
   frame, and 0x338 bytes of it have no C in src/ at all
   (config/arm9/overlays/ov085 names it; nothing decompiles it;
   nearmiss/db.jsonl holds a draft that does not byte-match).

   RABBIT is registered anyway, because on the castle grounds with a fresh
   save it is not reached: rabbit id 7 (MIPS) is the only one whose
   InitResources survives the save gate, and his own Behavior returns on its
   first line while data_0209caa0 word 2 bit 17 is clear. Measured both ways
   -- 3000 frames fault-free as the level boots, and this trap firing on frame
   one with the two save bits forced on. It names the function instead of
   jumping into the overlay image, which is what a hole should do. */
static void port_rabbit_state_0212b8dc(void *)
{
    std::fprintf(stderr, "FATAL: Rabbit state 0x021306cc's Main (ov085 "
                 "0x0212b8dc) is UNMATCHED -- no host body exists\n");
    std::abort();
}

static const struct { PortPmf *slot; unsigned rom; void (*host)(void *); }
g_rabbit_states[] = {
    {data_ov085_0213003c, 0x0212b4b4, func_ov085_0212b4b4},
    {data_ov085_02130044, 0x0212b8dc, port_rabbit_state_0212b8dc},
    {data_ov085_0213004c, 0x0212aaec, func_ov085_0212aaec},
    {data_ov085_02130054, 0x0212ad8c, func_ov085_0212ad8c},
    {data_ov085_0213005c, 0x0212b478, func_ov085_0212b478},
    {data_ov085_02130064, 0x0212b444, func_ov085_0212b444},
    {data_ov085_0213006c, 0x0212ac3c, func_ov085_0212ac3c},
    {data_ov085_02130074, 0x0212bc14, func_ov085_0212bc14},
    {data_ov085_0213007c, 0x0212b3fc, func_ov085_0212b3fc},
    {data_ov085_02130084, 0x0212b8a0, func_ov085_0212b8a0},
    {data_ov085_0213008c, 0x0212ae08, func_ov085_0212ae08},
    {data_ov085_02130094, 0x0212b86c, func_ov085_0212b86c},
    {data_ov085_0213009c, 0x0212ac4c, func_ov085_0212ac4c},
    {data_ov085_021300a4, 0x0212a904, func_ov085_0212a904},
    {data_ov085_021300ac, 0x0212aaa4, func_ov085_0212aaa4},
    {data_ov085_021300b4, 0x0212b75c, func_ov085_0212b75c},
};

static void port_rabbit_states_seat(void)
{
    for (unsigned i = 0; i < sizeof g_rabbit_states / sizeof g_rabbit_states[0];
         ++i) {
        PortPmf *p = g_rabbit_states[i].slot;
        if (p->fn != g_rabbit_states[i].rom || p->delta != 0) {
            std::fprintf(stderr, "FATAL: Rabbit state %u: the mount holds "
                         "%08x/%d, the ROM's own table says %08x/0 -- WRONG "
                         "BYTES\n", i, p->fn, p->delta,
                         g_rabbit_states[i].rom);
            std::abort();
        }
        p->fn = (unsigned)(size_t)g_rabbit_states[i].host;
    }
}

extern "C" void port_actor_overlays_sinits(void)
{
    static int done;
    if (done)
        return;
    done = 1;

    port_ov085_pack_check();
    port_ov085_syms_patch();
    port_lakitu_bro_states_seat();
    port_rabbit_states_seat();
    __sinit_ov085_0212f2a8();
    __sinit_ov085_0212f3a0();
    __sinit_ov085_0212f5ec();
    __sinit_ov085_0212f9bc();
    __sinit_ov085_0212fa40();
    __sinit_ov085_0212fdb0();

    port_ov098_pack_check();
    port_ov098_syms_patch();
    port_cannon_states_seat();
    __sinit_ov098_0213bf9c();
    __sinit_ov098_0213c058();
    __sinit_ov098_0213c214();
    __sinit_ov098_0213c2b4();

    port_ov089_pack_check();
    port_ov089_syms_patch();
    port_ov089_keymodels_fixup();
    __sinit_ov089_021328d4();

    port_ov100_pack_check();
    port_ov100_syms_patch();
    port_butterfly_states_seat();
    port_fish_states_seat();
    port_door_callbacks_seat();
    __sinit_ov100_021473bc();
    __sinit_ov100_021474e8();
    __sinit_ov100_021475a4();
    __sinit_ov100_02147698();
    __sinit_ov100_02147a70();
    __sinit_ov100_02147bc0();
    __sinit_ov100_02147d7c();

    port_ov102_pack_check();
    port_ov102_syms_patch();
    port_question_block_states_seat();
    __sinit_ov102_0214d714();
    __sinit_ov102_0214d908();
    __sinit_ov102_0214de70();
    __sinit_ov102_0214dfac();
}
