// Host file system: the card layer under SharedFilePtr.
//
// SEAM LEVEL: SharedFilePtr::Load(). Everything above it -- LoadFile's
// refcounting, Release, func_02017c24, func_02017e0c, and every
// Model/Animation/Collider LoadFile -- is portable src/ and runs verbatim.
// Load itself is card hardware (overlay-file table, card streaming, CP15
// cache flushes), so the HAL reimplements its CONTRACT: resolve fileID to
// bytes, decompress if LZ77-tagged, allocate the result from the game's own
// heap (gate 3a), stash filePtr, return it.
//
// ID NAMESPACES (the trap): callers construct with an ov0 HANDLE; the ctor
// helper func_02017e0c stores func_02018a24(handle) -- the FAT file id --
// into this->fileID. The HAL provides func_02018a24 from the asset catalog
// (build/assets/handles.tsv: handle -> file_id -> path, generated by
// tools/asset_catalog.py from the ROM). File bytes come from
// extracted/dsd/files/<path>.
//
// Construct is HAL-owned for an ABI reason, not a hardware one: on the DS,
// _ZN13SharedFilePtr9ConstructEj passes ov0FileID to func_02017e48 by
// LEAVING IT IN r1 across a call that only names one argument -- a
// ride-through C cannot express. The host version calls func_02017e0c with
// both arguments spelled out; same result, portable ABI.
//
// COMPRESSION: 1,287 catalog files begin with ASCII "LZ77" followed by a
// standard type-0x10 stream (u32 header: 0x10 | decompressed_size << 8).
// DecompressLZ16 is an asm hatch in src/, so the HAL carries a byte-wise
// C decode; the DS asm's halfword write dance is VRAM-safety only, the
// output bytes are identical (smoke_fs cross-checks against values computed
// by an independent Python decoder).
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

#ifndef PORT_REPO_ROOT
#define PORT_REPO_ROOT "."
#endif

// ---- the asset catalog ---------------------------------------------------
enum { MAX_FILES = 4096, MAX_HANDLES = 4096, PATH_MAX_ = 260 };

static char g_paths[MAX_FILES][PATH_MAX_]; /* by FAT file id */
static u16 g_handle_to_id[MAX_HANDLES];    /* ov0 handle -> FAT file id */
static int g_catalog_loaded;

static const char *asset_root(void)
{
    const char *env = getenv("SM64DS_ASSET_ROOT");
    return env ? env : PORT_REPO_ROOT;
}

static void catalog_load(void)
{
    char line[512], path[PATH_MAX_];
    FILE *f;
    if (g_catalog_loaded)
        return;
    g_catalog_loaded = 1;

    snprintf(path, sizeof path, "%s/build/assets/files.tsv", asset_root());
    f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "FATAL: fs catalog missing: %s\n"
                "       run tools/asset_catalog.py generate <rom>\n", path);
        abort();
    }
    fgets(line, sizeof line, f); /* header row */
    while (fgets(line, sizeof line, f)) {
        unsigned id;
        char p[PATH_MAX_];
        if (sscanf(line, "%u\t%*s\t%259[^\t]", &id, p) == 2 && id < MAX_FILES)
            strcpy(g_paths[id], p);
    }
    fclose(f);

    snprintf(path, sizeof path, "%s/build/assets/handles.tsv", asset_root());
    f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "FATAL: fs catalog missing: %s\n", path);
        abort();
    }
    fgets(line, sizeof line, f);
    while (fgets(line, sizeof line, f)) {
        unsigned h, id;
        if (sscanf(line, "%u\t%*s\t%u", &h, &id) == 2 && h < MAX_HANDLES)
            g_handle_to_id[h] = (u16)id;
    }
    fclose(f);
}

// ---- the game-facing surface ---------------------------------------------
// The Memory:: layer is real C++ on host (gate-3a slice), so the HAL calls
// the namespace; the C-linkage name below serves the C TUs (func_02017c24).
namespace Memory {
void *Allocate(u32 size);
void *Allocate(u32 size, int align);
void Deallocate(void *p);
}
extern "C" void _ZN6Memory10DeallocateEPv(void *p) { Memory::Deallocate(p); }

extern "C" {
u32 data_0209d3bc; /* last fileID touched; the game's FS breadcrumb */

/* ov0 handle -> FAT file id (data_ov000_020bd4b8 on the DS) */
u16 func_02018a24(u32 handle)
{
    catalog_load();
    if (handle >= 0x8000)
        return (u16)handle;   /* archive-interior: already a file id (DS
                                 original passes >= 0x8000 through) */
    if (handle >= MAX_HANDLES || g_paths[g_handle_to_id[handle]][0] == 0) {
        fprintf(stderr, "FATAL: fs handle %u not in catalog\n", handle);
        abort();
    }
    return g_handle_to_id[handle];
}

/* LZ77 type-0x10 decode; src points at the u32 header */
void DecompressLZ16(void *src_, void *dst_)
{
    const u8 *s = (const u8 *)src_;
    u8 *d = (u8 *)dst_;
    u32 size = (s[0] | s[1] << 8 | s[2] << 16 | (u32)s[3] << 24) >> 8;
    u32 out = 0;
    s += 4;
    while (out < size) {
        u8 flags = *s++;
        for (int bit = 0; bit < 8 && out < size; ++bit) {
            if (flags & (0x80 >> bit)) {
                u32 len = (s[0] >> 4) + 3;
                u32 disp = ((s[0] & 0xF) << 8 | s[1]) + 1;
                s += 2;
                while (len-- && out < size) {
                    d[out] = d[out - disp];
                    ++out;
                }
            } else {
                d[out++] = *s++;
            }
        }
    }
}

/* Archive-interior file IDs (>= 0x8000): the DS mounts 13 NARC archives
   whose id ranges live in the ROM's mount table; interior id - base
   indexes the NARC's own FAT. port_archive_map is the host-shaped copy
   romdata.py generates from that table. Each archive lazy-loads whole
   (they are small) and stays cached. */
struct port_arc_entry { u16 base, end; const char *narc; };
extern "C" struct port_arc_entry port_archive_map[13];
static u8 *g_arc_buf[13];
static long g_arc_len[13];

static void *port_fs_archive_load(unsigned fileID)
{
    for (int i = 0; i < 13; ++i) {
        struct port_arc_entry *e = &port_archive_map[i];
        if (fileID < e->base || fileID >= e->end)
            continue;
        if (!g_arc_buf[i]) {
            char path[PATH_MAX_ * 2];
            snprintf(path, sizeof path, "%s/extracted/dsd/files/%s",
                     asset_root(), e->narc);
            FILE *f = fopen(path, "rb");
            if (!f) {
                fprintf(stderr, "fs: archive missing on disk: %s\n", path);
                return 0;
            }
            fseek(f, 0, SEEK_END);
            g_arc_len[i] = ftell(f);
            fseek(f, 0, SEEK_SET);
            g_arc_buf[i] = (u8 *)malloc(g_arc_len[i]);
            if ((long)fread(g_arc_buf[i], 1, g_arc_len[i], f) != g_arc_len[i]) {
                fclose(f);
                free(g_arc_buf[i]);
                g_arc_buf[i] = 0;
                return 0;
            }
            fclose(f);
        }
        u8 *a = g_arc_buf[i];
        if (memcmp(a, "NARC", 4) != 0) {
            fprintf(stderr, "fs: %s is not a NARC\n", e->narc);
            return 0;
        }
        /* chunk walk: BTAF (fat), BTNF (names), GMIF (data) */
        u8 *btaf = a + 0x10;
        u32 btaf_size = btaf[4] | btaf[5] << 8 | btaf[6] << 16 | (u32)btaf[7] << 24;
        u16 nfiles = (u16)(btaf[8] | btaf[9] << 8);
        u8 *btnf = btaf + btaf_size;
        u32 btnf_size = btnf[4] | btnf[5] << 8 | btnf[6] << 16 | (u32)btnf[7] << 24;
        u8 *gmif = btnf + btnf_size;
        u8 *img = gmif + 8;
        unsigned idx = fileID - e->base;
        if (idx >= nfiles) {
            fprintf(stderr, "fs: interior %u out of range in %s (%u files)\n",
                    idx, e->narc, nfiles);
            return 0;
        }
        u8 *fat = btaf + 12 + idx * 8;
        u32 start = fat[0] | fat[1] << 8 | fat[2] << 16 | (u32)fat[3] << 24;
        u32 end = fat[4] | fat[5] << 8 | fat[6] << 16 | (u32)fat[7] << 24;
        u8 *src = img + start;
        u32 len = end - start;
        void *dst;
        if (len > 8 && memcmp(src, "LZ77", 4) == 0) {
            u32 dec = (src[4] | src[5] << 8 | src[6] << 16 | (u32)src[7] << 24) >> 8;
            dst = Memory::Allocate(dec);
            DecompressLZ16(src + 4, dst);
        } else {
            dst = Memory::Allocate(len, 0x20);
            memcpy(dst, src, len);
        }
        return dst;
    }
    fprintf(stderr, "FATAL: fs fileID 0x%x matches no archive range\n", fileID);
    abort();
}

/* SharedFilePtr::Load -- the seam. Same contract as 0x02017c54. */
struct SharedFilePtrC { u16 fileID; u8 numRefs; void *filePtr; };

void *_ZN13SharedFilePtr4LoadEv(struct SharedFilePtrC *self)
{
    char path[PATH_MAX_ * 2];
    FILE *f;
    long fsize;
    u8 *raw;
    void *dst;

    catalog_load();
    data_0209d3bc = self->fileID;
    if (self->fileID >= 0x8000) {
        void *b = port_fs_archive_load(self->fileID);
        if (b) self->filePtr = b;
        return b;
    }
    if (self->fileID >= MAX_FILES || g_paths[self->fileID][0] == 0) {
        fprintf(stderr, "FATAL: fs fileID %u not in catalog (fileptr %p)\n",
                self->fileID, (void *)self);
        abort();
    }
    snprintf(path, sizeof path, "%s/extracted/dsd/files/%s",
             asset_root(), g_paths[self->fileID]);
    f = fopen(path, "rb");
    if (!f) {
        /* a cataloged file missing on disk is a data hole (regional variants
           the extraction skipped), not a config error: fail like the real
           Load fails a short read, so callers see a null file */
        fprintf(stderr, "fs: missing on disk: %s\n", path);
        return 0;
    }
    fseek(f, 0, SEEK_END);
    fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    raw = (u8 *)malloc(fsize);
    if ((long)fread(raw, 1, fsize, f) != fsize) {
        fclose(f);
        free(raw);
        return 0; /* real Load returns 0 on a short read */
    }
    fclose(f);

    if (fsize > 8 && memcmp(raw, "LZ77", 4) == 0) {
        u32 dec = (raw[4] | raw[5] << 8 | raw[6] << 16 | (u32)raw[7] << 24) >> 8;
        dst = Memory::Allocate(dec);
        DecompressLZ16(raw + 4, dst);
    } else {
        dst = Memory::Allocate((u32)fsize, 0x20);
        memcpy(dst, raw, fsize);
    }
    free(raw);
    self->filePtr = dst;
    return dst;
}

// ---- the LOAD-AT pair (gate 24) ------------------------------------------
//
// LoadFileAt and LoadCompressedFileAt are the two entry points
// Stage::LoadGraphics2D fills the bottom screen through, and both are matched
// src that bottom out in the card layer this file replaces:
//
//     LoadFileAt(handle, dest)         -> func_02018270(handle, dest, -1)
//     LoadCompressedFileAt(id, target) -> func_0201817c(id), then the caller
//                                         reads the LZ header itself and
//                                         decompresses to target
//
// So func_0201817c has to hand back the file still COMPRESSED, with its u32
// LZ header at offset 0 -- LoadCompressedFileAt's own next two lines are
// `size = func_02018ac4(src)` (that header >> 8) and DecompressLZ16(src,
// target). SharedFilePtr::Load above cannot serve it: Load decompresses.
// Hence a raw sibling rather than a call into the seam.
//
// The extraction stores compressed files with a four-byte "LZ77" magic in
// front of the standard header; the card does not, so it is stripped here,
// exactly as Load does with its `raw + 4`.
/* The archive-interior case, without the decompression Load does: a pointer
   into the cached NARC image and the length of the member. Same chunk walk as
   port_fs_archive_load; that one copies and decodes, this one does not. */
static const u8 *port_fs_archive_slice(unsigned fileID, u32 *len_out)
{
    for (int i = 0; i < 13; ++i) {
        struct port_arc_entry *e = &port_archive_map[i];
        if (fileID < e->base || fileID >= e->end)
            continue;
        if (!g_arc_buf[i]) {
            /* port_fs_archive_load is what caches the archive image; its
               return value is a decoded copy this caller does not want. */
            void *throwaway = port_fs_archive_load(fileID);
            if (!throwaway)
                return 0;
            Memory::Deallocate(throwaway);
        }
        u8 *a = g_arc_buf[i];
        if (!a || memcmp(a, "NARC", 4) != 0)
            return 0;
        u8 *btaf = a + 0x10;
        u32 btaf_size = btaf[4] | btaf[5] << 8 | btaf[6] << 16 | (u32)btaf[7] << 24;
        u16 nfiles = (u16)(btaf[8] | btaf[9] << 8);
        u8 *btnf = btaf + btaf_size;
        u32 btnf_size = btnf[4] | btnf[5] << 8 | btnf[6] << 16 | (u32)btnf[7] << 24;
        u8 *img = btnf + btnf_size + 8;
        unsigned idx = fileID - e->base;
        if (idx >= nfiles)
            return 0;
        u8 *fat = btaf + 12 + idx * 8;
        u32 start = fat[0] | fat[1] << 8 | fat[2] << 16 | (u32)fat[3] << 24;
        u32 end = fat[4] | fat[5] << 8 | fat[6] << 16 | (u32)fat[7] << 24;
        *len_out = end - start;
        return img + start;
    }
    return 0;
}

static u8 *port_fs_read_raw(u32 handle, long *len_out)
{
    char path[PATH_MAX_ * 2];
    u32 fileID;
    catalog_load();
    fileID = func_02018a24(handle);
    /* Handles at or past 0x8000 are archive-interior ids -- the ones
       Stage::LoadGraphics2D uses for every one of its own files -- and they
       are not in the plain FAT catalog at all. */
    if (fileID >= 0x8000) {
        u32 alen = 0;
        const u8 *slice = port_fs_archive_slice(fileID, &alen);
        u8 *copy;
        if (!slice) {
            fprintf(stderr, "fs: load-at interior id 0x%x not found\n", fileID);
            return 0;
        }
        copy = (u8 *)malloc(alen ? alen : 1);
        memcpy(copy, slice, alen);
        *len_out = (long)alen;
        return copy;
    }
    if (fileID >= MAX_FILES || g_paths[fileID][0] == 0) {
        fprintf(stderr, "fs: load-at fileID %u (handle 0x%x) not in catalog\n",
                fileID, handle);
        return 0;
    }
    snprintf(path, sizeof path, "%s/extracted/dsd/files/%s", asset_root(),
             g_paths[fileID]);
    {
        FILE *f = fopen(path, "rb");
        long fsize;
        u8 *raw;
        if (!f) {
            fprintf(stderr, "fs: load-at missing on disk: %s\n", path);
            return 0;
        }
        fseek(f, 0, SEEK_END);
        fsize = ftell(f);
        fseek(f, 0, SEEK_SET);
        raw = (u8 *)malloc(fsize);
        if ((long)fread(raw, 1, fsize, f) != fsize) {
            fclose(f);
            free(raw);
            return 0;
        }
        fclose(f);
        *len_out = fsize;
        return raw;
    }
}

/* func_0201817c: the file, still compressed, on the game's own heap so the
   caller's Deallocate matches. */
void *func_0201817c(u32 handle)
{
    long len = 0;
    u8 *raw = port_fs_read_raw(handle, &len);
    void *dst;
    int magic;
    long blen;
    if (!raw)
        return 0;
    magic = len > 8 && memcmp(raw, "LZ77", 4) == 0;
    blen = magic ? len - 4 : len;
    dst = Memory::Allocate((u32)blen, 0x20);
    memcpy(dst, magic ? raw + 4 : raw, blen);
    free(raw);
    return dst;
}

/* func_02018270: the file's bytes straight to an address. The card reads raw,
   but a compressed file arriving here would mean the caller wanted
   LoadCompressedFileAt, so decode rather than write an LZ header into VRAM --
   and say so once, because it means the two are being confused. */
void func_02018270(u32 handle, u32 dest, int size)
{
    long len = 0;
    u8 *raw = port_fs_read_raw(handle, &len);
    if (!raw)
        return;
    if (len > 8 && memcmp(raw, "LZ77", 4) == 0) {
        static int said;
        if (!said++)
            fprintf(stderr, "fs: LoadFileAt(0x%x) on an LZ77 file; decoding\n",
                    handle);
        DecompressLZ16(raw + 4, (void *)dest);
    } else {
        if (size >= 0 && (long)size < len)
            len = size;
        memcpy((void *)dest, raw, len);
    }
    free(raw);
}

/* Construct: host ABI spells out both args (see header comment) */
void func_02017e0c(void *self, u32 arg); /* portable src/ */
struct SharedFilePtrC *_ZN13SharedFilePtr9ConstructEj(
        struct SharedFilePtrC *self, u32 ov0FileID)
{
    func_02017e0c(self, ov0FileID);
    return self;
}
} /* extern "C" */
