// Host file system: the card layer under SharedFilePtr.
//
// SEAM LEVEL: SharedFilePtr::Load(). Everything above it -- LoadFile's
// refcounting, Release, func_02017c24, func_02017e0c, and every
// Model/Animation/Collider LoadFile -- is portable src/ and runs verbatim.
// Load itself is card hardware (overlay-file table, card streaming, CP15
// cache flushes), so the HAL reimplements its CONTRACT: resolve fileID to
// bytes, decompress if LZ77-tagged, allocate the result from the game's own
// heap (gate 3a), stash filePtr, return it.
//
// ID NAMESPACES (the trap): callers construct with an ov0 HANDLE; the ctor
// helper func_02017e0c stores func_02018a24(handle) -- the FAT file id --
// into this->fileID. The HAL provides func_02018a24 from the asset catalog
// (build/assets/handles.tsv: handle -> file_id -> path, generated by
// tools/asset_catalog.py from the ROM). File bytes come from
// extracted/dsd/files/<path>.
//
// Construct is HAL-owned for an ABI reason, not a hardware one: on the DS,
// _ZN13SharedFilePtr9ConstructEj passes ov0FileID to func_02017e48 by
// LEAVING IT IN r1 across a call that only names one argument -- a
// ride-through C cannot express. The host version calls func_02017e0c with
// both arguments spelled out; same result, portable ABI.
//
// COMPRESSION: 1,287 catalog files begin with ASCII "LZ77" followed by a
// standard type-0x10 stream (u32 header: 0x10 | decompressed_size << 8).
// DecompressLZ16 is an asm hatch in src/, so the HAL carries a byte-wise
// C decode; the DS asm's halfword write dance is VRAM-safety only, the
// output bytes are identical (smoke_fs cross-checks against values computed
// by an independent Python decoder).
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

#ifndef PORT_REPO_ROOT
#define PORT_REPO_ROOT "."
#endif

// ---- the asset catalog ---------------------------------------------------
enum { MAX_FILES = 4096, MAX_HANDLES = 4096, PATH_MAX_ = 260 };

static char g_paths[MAX_FILES][PATH_MAX_]; /* by FAT file id */
static u16 g_handle_to_id[MAX_HANDLES];    /* ov0 handle -> FAT file id */
static int g_catalog_loaded;

static const char *asset_root(void)
{
    const char *env = getenv("SM64DS_ASSET_ROOT");
    return env ? env : PORT_REPO_ROOT;
}

static void catalog_load(void)
{
    char line[512], path[PATH_MAX_];
    FILE *f;
    if (g_catalog_loaded)
        return;
    g_catalog_loaded = 1;

    snprintf(path, sizeof path, "%s/build/assets/files.tsv", asset_root());
    f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "FATAL: fs catalog missing: %s\n"
                "       run tools/asset_catalog.py generate <rom>\n", path);
        abort();
    }
    fgets(line, sizeof line, f); /* header row */
    while (fgets(line, sizeof line, f)) {
        unsigned id;
        char p[PATH_MAX_];
        if (sscanf(line, "%u\t%*s\t%259[^\t]", &id, p) == 2 && id < MAX_FILES)
            strcpy(g_paths[id], p);
    }
    fclose(f);

    snprintf(path, sizeof path, "%s/build/assets/handles.tsv", asset_root());
    f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "FATAL: fs catalog missing: %s\n", path);
        abort();
    }
    fgets(line, sizeof line, f);
    while (fgets(line, sizeof line, f)) {
        unsigned h, id;
        if (sscanf(line, "%u\t%*s\t%u", &h, &id) == 2 && h < MAX_HANDLES)
            g_handle_to_id[h] = (u16)id;
    }
    fclose(f);
}

// ---- the game-facing surface ---------------------------------------------
// The Memory:: layer is real C++ on host (gate-3a slice), so the HAL calls
// the namespace; the C-linkage name below serves the C TUs (func_02017c24).
namespace Memory {
void *Allocate(u32 size);
void *Allocate(u32 size, int align);
void Deallocate(void *p);
}
extern "C" void _ZN6Memory10DeallocateEPv(void *p) { Memory::Deallocate(p); }

extern "C" {
u32 data_0209d3bc; /* last fileID touched; the game's FS breadcrumb */

/* ov0 handle -> FAT file id (data_ov000_020bd4b8 on the DS) */
u16 func_02018a24(u32 handle)
{
    catalog_load();
    if (handle >= 0x8000)
        return (u16)handle;   /* archive-interior: already a file id (DS
                                 original passes >= 0x8000 through) */
    if (handle >= MAX_HANDLES || g_paths[g_handle_to_id[handle]][0] == 0) {
        fprintf(stderr, "FATAL: fs handle %u not in catalog\n", handle);
        abort();
    }
    return g_handle_to_id[handle];
}

/* LZ77 type-0x10 decode; src points at the u32 header */
void DecompressLZ16(void *src_, void *dst_)
{
    const u8 *s = (const u8 *)src_;
    u8 *d = (u8 *)dst_;
    u32 size = (s[0] | s[1] << 8 | s[2] << 16 | (u32)s[3] << 24) >> 8;
    u32 out = 0;
    s += 4;
    while (out < size) {
        u8 flags = *s++;
        for (int bit = 0; bit < 8 && out < size; ++bit) {
            if (flags & (0x80 >> bit)) {
                u32 len = (s[0] >> 4) + 3;
                u32 disp = ((s[0] & 0xF) << 8 | s[1]) + 1;
                s += 2;
                while (len-- && out < size) {
                    d[out] = d[out - disp];
                    ++out;
                }
            } else {
                d[out++] = *s++;
            }
        }
    }
}

/* Archive-interior file IDs (>= 0x8000): the DS mounts 13 NARC archives
   whose id ranges live in the ROM's mount table; interior id - base
   indexes the NARC's own FAT. port_archive_map is the host-shaped copy
   romdata.py generates from that table. Each archive lazy-loads whole
   (they are small) and stays cached. */
struct port_arc_entry { u16 base, end; const char *narc; };
extern "C" struct port_arc_entry port_archive_map[13];
static u8 *g_arc_buf[13];
static long g_arc_len[13];

struct fs_cache_entry;
static int fs_entry_store(struct fs_cache_entry *e, const u8 *src, u32 len);

/* fill e with the decompressed bytes of an archive-interior file. 1 on
   success, 0 on a data hole; aborts only where the original did. */
static int port_fs_archive_fill(struct fs_cache_entry *ent, unsigned fileID)
{
    for (int i = 0; i < 13; ++i) {
        struct port_arc_entry *e = &port_archive_map[i];
        if (fileID < e->base || fileID >= e->end)
            continue;
        if (!g_arc_buf[i]) {
            char path[PATH_MAX_ * 2];
            snprintf(path, sizeof path, "%s/extracted/dsd/files/%s",
                     asset_root(), e->narc);
            FILE *f = fopen(path, "rb");
            if (!f) {
                fprintf(stderr, "fs: archive missing on disk: %s\n", path);
                return 0;
            }
            fseek(f, 0, SEEK_END);
            g_arc_len[i] = ftell(f);
            fseek(f, 0, SEEK_SET);
            g_arc_buf[i] = (u8 *)malloc(g_arc_len[i]);
            if ((long)fread(g_arc_buf[i], 1, g_arc_len[i], f) != g_arc_len[i]) {
                fclose(f);
                free(g_arc_buf[i]);
                g_arc_buf[i] = 0;
                return 0;
            }
            fclose(f);
        }
        u8 *a = g_arc_buf[i];
        if (memcmp(a, "NARC", 4) != 0) {
            fprintf(stderr, "fs: %s is not a NARC\n", e->narc);
            return 0;
        }
        /* chunk walk: BTAF (fat), BTNF (names), GMIF (data) */
        u8 *btaf = a + 0x10;
        u32 btaf_size = btaf[4] | btaf[5] << 8 | btaf[6] << 16 | (u32)btaf[7] << 24;
        u16 nfiles = (u16)(btaf[8] | btaf[9] << 8);
        u8 *btnf = btaf + btaf_size;
        u32 btnf_size = btnf[4] | btnf[5] << 8 | btnf[6] << 16 | (u32)btnf[7] << 24;
        u8 *gmif = btnf + btnf_size;
        u8 *img = gmif + 8;
        unsigned idx = fileID - e->base;
        if (idx >= nfiles) {
            fprintf(stderr, "fs: interior %u out of range in %s (%u files)\n",
                    idx, e->narc, nfiles);
            return 0;
        }
        u8 *fat = btaf + 12 + idx * 8;
        u32 start = fat[0] | fat[1] << 8 | fat[2] << 16 | (u32)fat[3] << 24;
        u32 end = fat[4] | fat[5] << 8 | fat[6] << 16 | (u32)fat[7] << 24;
        return fs_entry_store(ent, img + start, end - start);
    }
    fprintf(stderr, "FATAL: fs fileID 0x%x matches no archive range\n", fileID);
    abort();
}

/* ---- host file cache ----------------------------------------------------
   WHY: SharedFilePtr is refcounted, and every file whose count reaches zero
   is Deallocate'd by func_02017c24 and re-read on the next reference. That
   is right for a DS with 4 MB of RAM and a card that streams; on a host it
   means Player::SetAnim does a blocking fopen + fread + LZ77 decode on the
   frame the animation changes (see src/_ZN6Player7SetAnimEji5Fix12IiEj.cpp:
   Release(old) immediately followed by LoadFile(new)). That was the frame
   hitch on jumps.

   The cache sits entirely under the seam and changes no observable contract:
   it keeps its own master copy of the DECOMPRESSED bytes and still hands the
   caller a fresh Memory::Allocate'd buffer on every Load, allocated with the
   same call shape the uncached path used (1-arg for LZ77 output, 0x20-aligned
   for stored files). The game remains free to write into what it is given and
   to Deallocate it; the next Load gets pristine bytes, exactly as a re-read
   from the card would. The master is snapshotted at decode time, before the
   caller can touch it, so a mutating caller cannot poison the cache.

   BOTH id namespaces are cached. Measured on a 300-frame castle-grounds walk:
   145 loads at boot (86 loose + 59 archive) and only 3 during play, and all
   three of those were archive-interior -- the Player's animations live inside
   a NARC, so a loose-file-only cache would never have served one. The archive
   path is cheaper than the loose one (the NARC itself is already resident) but
   it still LZ77-decodes per load, so it gets the same treatment. */
struct fs_cache_entry {
    u8 *data;   /* master copy: decompressed bytes, malloc'd, never handed out */
    u32 size;
    int align;  /* 0 = Memory::Allocate(size); else Allocate(size, align) */
    int valid;
};
/* indexed by fileID; SharedFilePtr::fileID is a u16, so one flat lazily
   allocated table covers loose files and archive interiors alike */
enum { FS_CACHE_SLOTS = 0x10000 };
static struct fs_cache_entry *g_fcache;
static unsigned long g_fcache_bytes, g_fcache_files;
static unsigned long g_fs_hits, g_fs_misses;
static int g_fcache_capped;

static struct fs_cache_entry *fs_slot(unsigned fileID)
{
    if (!g_fcache)
        g_fcache = (struct fs_cache_entry *)
                   calloc(FS_CACHE_SLOTS, sizeof *g_fcache);
    return g_fcache && fileID < FS_CACHE_SLOTS ? &g_fcache[fileID] : 0;
}

/* copy len bytes of file image into e's master, decompressing if LZ77-tagged.
   Records the allocation shape the uncached path would have used. */
static int fs_entry_store(struct fs_cache_entry *e, const u8 *src, u32 len)
{
    if (len > 8 && memcmp(src, "LZ77", 4) == 0) {
        u32 dec = (src[4] | src[5] << 8 | src[6] << 16 | (u32)src[7] << 24) >> 8;
        e->data = (u8 *)malloc(dec ? dec : 1);
        if (!e->data) return 0;
        DecompressLZ16((void *)(src + 4), e->data);
        e->size = dec;
        e->align = 0;
    } else {
        e->data = (u8 *)malloc(len ? len : 1);
        if (!e->data) return 0;
        memcpy(e->data, src, len);
        e->size = len;
        e->align = 0x20;
    }
    return 1;
}

/* keep-all is fine at castle-grounds sizes; the cap only exists so a long or
   pathological run cannot grow without bound. Blocked admissions still load,
   they just go to disk. */
static unsigned long fs_cache_max(void)
{
    const char *e = getenv("SM64DS_FS_CACHE_MAX");
    return e ? strtoul(e, 0, 0) : 128UL * 1024 * 1024;
}

static int fs_env_on(const char *name)
{
    const char *e = getenv(name);
    return e && *e && *e != '0';
}

static int fs_trace_on(void)
{
    static int v = -1;
    if (v < 0) v = fs_env_on("SM64DS_FS_TRACE");
    return v;
}

static int fs_cache_off(void)
{
    static int v = -1;
    if (v < 0) v = fs_env_on("SM64DS_FS_NOCACHE");
    return v;
}

static void fs_cache_report(void)
{
    fprintf(stderr, "fs: cache %lu files, %lu bytes resident; %lu hits, "
            "%lu misses%s\n", g_fcache_files, g_fcache_bytes, g_fs_hits,
            g_fs_misses, g_fcache_capped ? " (cap reached)" : "");
}

/* read + decompress a loose FAT file into e's master copy. 1 on success. */
static int fs_cache_fill(struct fs_cache_entry *e, unsigned fileID)
{
    char path[PATH_MAX_ * 2];
    FILE *f;
    long fsize;
    u8 *raw;
    int ok;

    snprintf(path, sizeof path, "%s/extracted/dsd/files/%s",
             asset_root(), g_paths[fileID]);
    f = fopen(path, "rb");
    if (!f) {
        /* a cataloged file missing on disk is a data hole (regional variants
           the extraction skipped), not a config error: fail like the real
           Load fails a short read, so callers see a null file */
        fprintf(stderr, "fs: missing on disk: %s\n", path);
        return 0;
    }
    fseek(f, 0, SEEK_END);
    fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    raw = (u8 *)malloc(fsize);
    if ((long)fread(raw, 1, fsize, f) != fsize) {
        fclose(f);
        free(raw);
        return 0; /* real Load returns 0 on a short read */
    }
    fclose(f);
    ok = fs_entry_store(e, raw, (u32)fsize);
    free(raw);
    return ok;
}

/* hand the caller its own buffer, allocated the way the uncached path did */
static void *fs_hand_out(const struct fs_cache_entry *e)
{
    void *dst = e->align ? Memory::Allocate(e->size, e->align)
                         : Memory::Allocate(e->size);
    if (dst)
        memcpy(dst, e->data, e->size);
    return dst;
}

/* SharedFilePtr::Load -- the seam. Same contract as 0x02017c54. */
struct SharedFilePtrC { u16 fileID; u8 numRefs; void *filePtr; };

void *_ZN13SharedFilePtr4LoadEv(struct SharedFilePtrC *self)
{
    struct fs_cache_entry *e, tmp;
    const int archive = self->fileID >= 0x8000;
    const char *src;
    int cached, admit, ok;
    u32 tsize;
    void *dst;

    catalog_load();
    data_0209d3bc = self->fileID;
    if (!archive && (self->fileID >= MAX_FILES ||
                     g_paths[self->fileID][0] == 0)) {
        fprintf(stderr, "FATAL: fs fileID %u not in catalog (fileptr %p)\n",
                self->fileID, (void *)self);
        abort();
    }

    e = fs_slot(self->fileID);
    cached = e && e->valid;
    if (cached) {
        g_fs_hits++;
        tsize = e->size;
        dst = fs_hand_out(e);
        src = "cache";
    } else {
        struct fs_cache_entry *slot;
        admit = e && !fs_cache_off() && g_fcache_bytes < fs_cache_max();
        slot = admit ? e : &tmp;
        memset(slot, 0, sizeof *slot);
        ok = archive ? port_fs_archive_fill(slot, self->fileID)
                     : fs_cache_fill(slot, self->fileID);
        if (!ok) {
            if (slot->data) { free(slot->data); slot->data = 0; }
            return 0;
        }
        if (admit) {
            slot->valid = 1;
            g_fcache_bytes += slot->size;
            if (++g_fcache_files == 1 && fs_trace_on())
                atexit(fs_cache_report);
        } else if (e && !fs_cache_off()) {
            g_fcache_capped = 1;
        }
        g_fs_misses++;
        tsize = slot->size;
        dst = fs_hand_out(slot);
        if (!admit) {
            free(slot->data);
            slot->data = 0;
        }
        src = archive ? "archive" : "disk";
    }

    if (fs_trace_on())
        fprintf(stderr, "fs: load id=%u size=%u source=%s\n",
                self->fileID, tsize, src);
    if (dst)
        self->filePtr = dst;
    return dst;
}

/* Construct: host ABI spells out both args (see header comment) */
void func_02017e0c(void *self, u32 arg); /* portable src/ */
struct SharedFilePtrC *_ZN13SharedFilePtr9ConstructEj(
        struct SharedFilePtrC *self, u32 ov0FileID)
{
    func_02017e0c(self, ov0FileID);
    return self;
}
} /* extern "C" */
