// GENERATED by port/tools/facegen.py -- the mechanical rows only.
// Every face here passed the exact-name join and the arity gate;
// what no generator checks is method_faces.cpp's checklist item
// (a), the plausible-sibling trap, so review each row's target
// against its caller before wiring. This file includes NOTHING,
// for hal/actor_class_faces.cpp's reasons.



#pragma comment(linker, "/alternatename:?data_0208e4b8@@3PAHA=_data_0208e4b8")
#pragma comment(linker, "/alternatename:?data_0209d4b8@@3HA=_data_0209d4b8")
#pragma comment(linker, "/alternatename:?data_0209f61c@@3PAXA=_data_0209f61c")
#pragma comment(linker, "/alternatename:?data_ov004_020bc0c0@@3PAHA=_data_ov004_020bc0c0")
#pragma comment(linker, "/alternatename:?data_ov004_020bc7d4@@3PAXA=_data_ov004_020bc7d4")
#pragma comment(linker, "/alternatename:?data_ov004_020bc86c@@3HA=_data_ov004_020bc86c")
#pragma comment(linker, "/alternatename:?data_ov004_020bc898@@3HA=_data_ov004_020bc898")
#pragma comment(linker, "/alternatename:?data_ov004_020bc8a4@@3HA=_data_ov004_020bc8a4")
#pragma comment(linker, "/alternatename:?data_ov004_020bc8a8@@3HA=_data_ov004_020bc8a8")
#pragma comment(linker, "/alternatename:?data_ov004_020beb68@@3PAHA=_data_ov004_020beb68")
#pragma comment(linker, "/alternatename:?data_ov004_020beb68@@3PAUBase@@A=_data_ov004_020beb68")
#pragma comment(linker, "/alternatename:?data_ov004_020beb68@@3PAUObj@@A=_data_ov004_020beb68")
#pragma comment(linker, "/alternatename:?data_ov004_020beb68@@3PAXA=_data_ov004_020beb68")
#pragma comment(linker, "/alternatename:?data_ov004_020bf3e8@@3PAEA=_data_ov004_020bf3e8")
#pragma comment(linker, "/alternatename:?data_ov004_020bf428@@3PAUPair@@A=_data_ov004_020bf428")
#pragma comment(linker, "/alternatename:?data_ov004_020bf4f8@@3PAUPair@@A=_data_ov004_020bf4f8")
#pragma comment(linker, "/alternatename:?data_ov004_020bf560@@3PAHA=_data_ov004_020bf560")
#pragma comment(linker, "/alternatename:?data_ov004_020bf5d4@@3PAHA=_data_ov004_020bf5d4")
#pragma comment(linker, "/alternatename:?data_ov004_020bfa24@@3PAXA=_data_ov004_020bfa24")
