#!/usr/bin/env python3
"""Generate host-only type declarations without changing ROM-verified headers."""

import argparse
from pathlib import Path


def generate(root: Path, output: Path) -> None:
    original = (root / 'include/types.h').read_text(encoding='utf-8')
    before = '#ifdef _MSC_VER\n#include <stddef.h>'
    after = '#if defined(_MSC_VER) || defined(SM64DS_PLATFORM_PC)\n#include <stddef.h>'
    if original.count(before) != 1:
        raise ValueError('The size_t declaration changed; review the native-header adaptation')
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        '// Generated by port/tools/native_headers.py; ROM headers are untouched.\n'
        '#ifndef SM64DS_PLATFORM_PC\n#error Native types are for the host build only\n#endif\n'
        + original.replace(before, after), encoding='utf-8')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--out', type=Path, required=True)
    options = parser.parse_args()
    generate(options.root.resolve(), options.out.resolve())


if __name__ == '__main__':
    main()
