#!/usr/bin/env python3
"""Emit overlay data symbols as C arrays, bytes from the overlay image.

The Player (and every overlay actor) reads static tables baked into its
overlay's data section: animation-file entries, state objects, tuning
constants. Host symbols need that content, so this reads the overlay
binary plus its symbols.txt (sizes = next-symbol deltas) and emits real
bytes for a requested symbol list. Never committed: Nintendo bytes stay
out of git, same policy as romdata.py.

DS-code POINTERS inside emitted data (state Init/Main/Cleanup slots and
the like) are meaningless on host; callers patch those fields at runtime
with host addresses -- see the gate-10 smoke.

    python tools/ovdata.py <ovNNN> <out.c> <symbol> [symbol...]
    python tools/ovdata.py ov002 out.c --from-list syms.txt
    python tools/ovdata.py ov009 out.c --whole

--whole emits the ENTIRE overlay as one aligned array plus a reloc-driven
rebase (see whole_mode below). Per-symbol emission is wrong for a level
overlay: the LVL_Overlay's object tables are walked across symbol boundaries
by count, so eight separate host arrays put a neighbour's bytes wherever the
walk steps past the symbol dsd happened to name.
"""

import pathlib
import re
import struct
import sys


def overlay_yaml(root, ovid, field):
    """A field out of ONE overlay's record in overlays.yaml.

    The record is found by its own `- id:` line and nothing else. Matching
    "id: NN" anywhere in the file also matches the `file_id: NN` line of a
    DIFFERENT overlay -- ov085's base came back as ov043's that way, and the
    only symptom was the BL guard below firing on a byte that was never code.
    """
    ytxt = (root / "extracted/dsd/arm9_overlays/overlays.yaml").read_text()
    blk = re.search(rf"^  - id: {ovid}$\n(.*?)(?=^  - id: |\Z)", ytxt,
                    re.S | re.M)
    if not blk:
        sys.exit(f"overlays.yaml has no record for overlay {ovid}")
    m = re.search(rf"^    {field}: (\d+)$", blk.group(1), re.M)
    if not m:
        sys.exit(f"overlays.yaml: overlay {ovid} has no {field}")
    return int(m.group(1))


def load_relocs(root, ov):
    """{site address: target address} for every kind:load reloc."""
    relocs = {}
    rel_path = root / f"config/arm9/overlays/{ov}/relocs.txt"
    if rel_path.exists():
        for line in rel_path.read_text().splitlines():
            mm = re.search(r"from:0x([0-9a-fA-F]+)\s+kind:load\s+to:0x([0-9a-fA-F]+)",
                           line)
            if mm:
                relocs[int(mm.group(1), 16)] = int(mm.group(2), 16)
    return relocs


def whole_mode(root, ov, ovid, base, data, out_path):
    """Emit the overlay image as ONE array + a reloc-driven internal rebase.

    A DS overlay is linked at a fixed base and loaded there unrelocated, so
    the ROM image already holds absolute addresses. relocs.txt is a DELINKING
    artefact: it records which words are addresses and where they point. That
    is exactly the information a host mount needs -- every word the table says
    targets inside this overlay gets rewritten to the host array, and nothing
    else is touched. No value-range guessing: a data word that merely happens
    to look like an overlay address stays the number it is.

    bss lives past the file image (the loader zeroes it), so the host array is
    code_size + bss_size and pointers into bss land inside it too.
    """
    bss = overlay_yaml(root, ovid, "bss_size")
    total = len(data) + bss
    win = (base, base + total)
    relocs = load_relocs(root, ov)

    patches = []
    for site in sorted(relocs):
        target = relocs[site]
        if not (win[0] <= target < win[1]):
            continue                      # points at arm9 or another overlay
        off = site - base
        if not (0 <= off < len(data) - 3):
            continue                      # site itself is not file-backed
        word = int.from_bytes(data[off:off + 4], "little")
        if word != target:
            sys.exit(f"{ov}: reloc site {site:#010x} holds {word:#010x} but "
                     f"relocs.txt says {target:#010x} -- image/config desync")
        patches.append((off, target - base))

    # Report (do not act on) aligned words that LOOK like internal pointers
    # but carry no reloc. A real one would mean the delink table is short and
    # some host pointer walk will step off the array; guessing instead would
    # corrupt ordinary data that happens to sit in the window.
    known = {off for off, _ in patches}
    unlisted = 0
    for off in range(0, len(data) - 3, 4):
        if off in known:
            continue
        v = int.from_bytes(data[off:off + 4], "little")
        if win[0] <= v < win[1]:
            unlisted += 1

    body = ",".join(str(b) for b in data)
    tag = f"port_{ov}"
    lines = [
        f"/* GENERATED by port/tools/ovdata.py --whole from {ov}.bin"
        " -- local only. */",
        "typedef unsigned char u8;",
        "",
        f"/* {len(data):#x} bytes of image + {bss:#x} of bss, one object so the"
        " game's",
        " * table walks stay inside it however far past a symbol they step. */",
        f"__declspec(align(8)) u8 {tag}_image[{total}] = {{ {body} }};",
        f"const unsigned {tag}_ds_base = {base:#010x}u;",
        f"const unsigned {tag}_ds_end = {base + total:#010x}u;",
        "",
        "/* (word offset, target offset) for every reloc that points inside"
        " this overlay */",
        f"static const unsigned {tag}_rebase[][2] = {{",
    ]
    for off, tgt in patches:
        lines.append("    { %du, %du }," % (off, tgt))
    lines += [
        "};",
        "",
        f"void {tag}_patch(void)",
        "{",
        "    unsigned i;",
        f"    for (i = 0; i < sizeof {tag}_rebase / sizeof {tag}_rebase[0];"
        " ++i)",
        f"        *(unsigned *)({tag}_image + {tag}_rebase[i][0]) =",
        f"            (unsigned)(unsigned long){tag}_image + {tag}_rebase[i][1];",
        "}",
        "",
        "/* DS address -> host address inside the mounted image. Returns 0 for"
        " an",
        " * address outside the overlay so a caller can fail loudly rather"
        " than",
        " * hand the game a wild pointer. */",
        f"void *{tag}_at(unsigned ds)",
        "{",
        f"    if (ds < {tag}_ds_base || ds >= {tag}_ds_end) return 0;",
        f"    return {tag}_image + (ds - {tag}_ds_base);",
        "}",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"{ov} whole image {total:#x} bytes, {len(patches)} internal "
          f"pointers rebased ({unlisted} unlisted candidates) -> {out_path}")


def main():
    root = pathlib.Path(__file__).resolve().parents[2]
    ov = sys.argv[1]
    out_path = pathlib.Path(sys.argv[2])
    whole = sys.argv[3] == "--whole"
    pack = "--pack" in sys.argv
    if whole:
        wanted = []
    elif sys.argv[3] == "--from-list":
        text = "\n".join(
            ln for ln in pathlib.Path(sys.argv[4]).read_text().splitlines()
            if not ln.lstrip().startswith("#"))
        wanted = list(dict.fromkeys(w for w in text.split() if w != "--pack"))
    else:
        wanted = [a for a in sys.argv[3:] if a != "--pack"]

    ovid = int(ov[2:])
    base = overlay_yaml(root, ovid, "base_address")

    # Read the RAW ndspy overlay (tools/unpack.py output), not the dsd
    # export: the dsd image goes stale against config re-addressings
    # (found the hard way: a +0x12c drift left every non-reloc'd word --
    # jump velocities, anim IDs -- reading a stranger's bytes, while the
    # reloc-patched pointers hid the skew). The raw image is the ROM; the
    # yaml base still holds. Guard: a known arm_call from relocs.txt must
    # decode as BL, or the extraction itself is suspect.
    img = root / f"extracted/overlays/overlay_{ovid:04d}.bin"
    if not img.exists():
        img = root / f"extracted/dsd/arm9_overlays/{ov}.bin"
    data = img.read_bytes()
    rl = (root / f"config/arm9/overlays/{ov}/relocs.txt").read_text()
    mc = re.search(r"from:0x([0-9a-f]{8}) kind:arm_call", rl)
    if mc:
        probe = int(mc.group(1), 16) - base
        word = int.from_bytes(data[probe:probe + 4], "little")
        assert (word >> 24) == 0xEB, (
            f"{img}: first arm_call site 0x{mc.group(1)} is not a BL "
            f"(0x{word:08x}) -- image/config desync, re-extract")

    if whole:
        whole_mode(root, ov, ovid, base, data, out_path)
        return

    # every symbol in the overlay, sorted by address, for size deltas
    syms = []
    for line in (root / f"config/arm9/overlays/{ov}/symbols.txt").read_text().splitlines():
        mm = re.search(r"^(\S+)\s+kind:\S+\s+addr:0x([0-9a-fA-F]+)", line)
        if mm:
            syms.append((int(mm.group(2), 16), mm.group(1)))
    syms.sort()
    addr_of = {n: a for a, n in syms}

    # The DS applies the overlay's relocation table at load: the static image
    # holds pre-reloc junk where a pointer will live, and relocs.txt records
    # word-address -> target. Apply those before emitting, or every baked
    # pointer is garbage (build-time leftovers, ASCII scraps).
    relocs = load_relocs(root, ov)

    def reloc_blob(a, blob):
        b = bytearray(blob)
        for off in range(0, len(b) - 3, 4):
            t = relocs.get(a + off)
            if t is not None:
                b[off:off + 4] = t.to_bytes(4, "little")
        return bytes(b)

    lines = [f"/* GENERATED by port/tools/ovdata.py from {ov}.bin -- local only. */",
             "typedef unsigned char u8;", ""]
    # --pack: THE SYMBOLS KEEP THEIR ROM SPACING.
    #
    # dsd names a symbol wherever code happened to reference one, so a single
    # ROM object comes back as a run of neighbours -- ov009's water spawn
    # points are three seven-element Vector3 arrays split into twenty-one
    # symbols, and the loader walks each one by index. Separate host arrays
    # put element 1 wherever the linker felt like it.
    #
    # Grouped sections put the run back: MSVC sorts contributions by the part
    # after the `$`, so emitting every symbol in address order with explicit
    # padding for the gaps reproduces the ROM's own relative offsets exactly.
    # The generator refuses a layout it cannot express (a symbol whose size
    # would overlap its successor) and the emitted check asserts the result
    # at runtime rather than trusting the linker.
    pack_rows = []
    emitted = []          # (name, ds_addr, size)
    for name in wanted:
        # "name:0xNNN" pins the size -- for tables the game indexes past an
        # interior symbol (next-symbol deltas under-size those; on the DS the
        # memory is contiguous, on host separate arrays would break it).
        override = None
        if ":" in name:
            name, _, ov_sz = name.partition(":")
            override = int(ov_sz, 0)
        if name not in addr_of:
            sys.exit(f"{name} not in {ov} symbols")
        a = addr_of[name]
        nxt = next((s for s, _ in syms if s > a), a + 4)
        size = override if override else max(4, nxt - a)
        off = a - base
        blob = data[off:off + size]
        if len(blob) < size:
            blob = blob + b"\0" * (size - len(blob))   # tail runs into bss
        blob = reloc_blob(a, blob)
        body = ",".join(str(b) for b in blob)
        if pack:
            pack_rows.append((a, name, size, body))
        else:
            lines.append(f"u8 {name}[{size}] = {{ {body} }};")
        emitted.append((name, a, size, blob))

    if pack:
        tag = f"pk{ovid:03d}"
        pack_rows.sort()
        slot = 0
        prev_end = None
        checks = []
        first = pack_rows[0][0] if pack_rows else 0

        # EACH SYMBOL KEEPS ITS OWN ROM ALIGNMENT, not a blanket 4.
        # dsd names symbols wherever code referenced one, and some of those
        # land mid-word -- ov085 has three (a string interior and two
        # sub-fields). Declaring those align(4) makes MSVC pad the run and
        # every symbol after them shifts, which is exactly what the emitted
        # check caught: "data_ov085_0212ffff at +3460, ROM says +3459", and
        # then a 4-byte skew through the rest of the overlay's data.
        def rom_align(addr):
            return 4 if addr % 4 == 0 else (2 if addr % 2 == 0 else 1)

        for a, name, size, body in pack_rows:
            if prev_end is not None and a < prev_end:
                sys.exit(f"{ov}: --pack: {name} at {a:#010x} overlaps the "
                         f"symbol ending at {prev_end:#010x}")
            if prev_end is not None and a > prev_end:
                gap = a - prev_end
                lines.append(
                    f'__pragma(section(".{tag}${slot:04d}", read, write))'
                    f' __declspec(allocate(".{tag}${slot:04d}"))'
                    f' __declspec(align({rom_align(prev_end)}))'
                    f' static u8 {tag}_gap_{prev_end:08x}'
                    f'[{gap}] = {{ 0 }};')
                slot += 1
            lines.append(
                f'__pragma(section(".{tag}${slot:04d}", read, write))'
                f' __declspec(allocate(".{tag}${slot:04d}"))'
                f' __declspec(align({rom_align(a)}))'
                f' u8 {name}[{size}] = {{ {body} }};')
            slot += 1
            prev_end = a + size
            checks.append((name, a - first))
        lines.append("")
        lines.append("#include <stdio.h>")
        lines.append(f"void port_{ov}_pack_check(void)")
        lines.append("{")
        lines.append(f"    const u8 *base = {pack_rows[0][1]};")
        for name, off in checks:
            lines.append(f"    if ({name} - base != {off})")
            lines.append(
                '        fprintf(stderr, "  [%s] PACK BROKEN: %s at +%%d, '
                'ROM says +%d\\n", (int)(%s - base));' % (ov, name, off, name))
        lines.append("}")

    # Un-symbolized statics: mwcc pools some SharedFilePtr objects and small
    # tables in the overlay tail (0x0210xxxx) where dsd attributed the range
    # to the giant sinit functions. Any pointer in emitted data landing there
    # gets a synthetic gap block (real overlay bytes) so the walks stay on
    # hosted storage. Iterated: gap blocks can reference further gaps.
    DATA_WIN = (0x02100000, base + len(data) + 0x1000)
    if pack:
        # A LEVEL overlay's data holds its own CODE addresses -- the Bird's
        # four behaviour states are {function, 0} pairs sitting in .data -- and
        # mounting the text section as a synthetic data block would rebase them
        # onto host bytes that are not the host function. The seat that patches
        # those pairs cross-checks the stored word against the ROM address, so
        # the wrong answer would be caught, but it must not be produced in the
        # first place. Start the window at the end of .text.
        dl = (root / f"config/arm9/overlays/{ov}/delinks.txt").read_text()
        mt = re.search(r"\.text\s+start:0x([0-9a-fA-F]+)\s+end:0x([0-9a-fA-F]+)",
                       dl)
        if mt:
            DATA_WIN = (int(mt.group(2), 16), DATA_WIN[1])
    for _ in range(5):
        cov = sorted((a, a + sz) for _, a, sz, _ in emitted)

        def covered(v):
            for s, e in cov:
                if s <= v < e:
                    return True
            return False

        want = set()
        for _, _, _, blob in emitted:
            for off in range(0, len(blob) - 3, 4):
                v = int.from_bytes(blob[off:off + 4], "little")
                if DATA_WIN[0] <= v < DATA_WIN[1] and not covered(v):
                    want.add(v)
        if not want:
            break
        runs = []
        for t in sorted(want):
            if runs and t - runs[-1][1] <= 0x100:
                runs[-1][1] = t + 0x18
            else:
                runs.append([t, t + 0x18])
        for s, e in runs:
            name = "port_%s_gap_%08x" % (ov, s)
            blob = data[s - base:e - base]
            if len(blob) < e - s:
                blob = blob + b"\0" * (e - s - len(blob))
            blob = reloc_blob(s, blob)
            body = ",".join(str(b) for b in blob)
            lines.append(f"u8 {name}[{e - s}] = {{ {body} }};")
            emitted.append((name, s, e - s, blob))

    # Pointer relocation: emitted data holds DS addresses of OTHER emitted
    # symbols (fileptr tables, dtor-chain nodes). Rewrite any aligned word
    # that lands inside another emitted symbol to the host address, so the
    # game's pointer walks stay on hosted storage. Code pointers and words
    # pointing at un-hosted data are left as-is (they trap loudly).
    ivals = sorted((a, a + sz, n) for n, a, sz, _ in emitted)
    import bisect
    starts = [iv[0] for iv in ivals]
    widest = max((e - s for s, e, _ in ivals), default=0)

    # SYMBOLS OVERLAP, so the nearest preceding start is not the answer.
    # A synthetic gap block is one run covering every un-symbolized target in
    # a 0x100 neighbourhood, and named symbols sit inside it: ov002's
    # port_ov002_gap_0210c548 is 1452 bytes and swallows six of them, the
    # first being OAM::MM_STAR_MARKERS at 0x0210c5b8. A lookup that stopped at
    # the nearest start answered "MM_STAR_MARKERS" for every target past
    # 0x0210c5b8, found it did not reach, and returned NOTHING -- so those
    # pointers stayed raw DS addresses.
    #
    # What that costs: HUD::RenderHealthMeter reads its sprite list out of
    # data_ov002_0210c230, whose nine entries all point at 0x0210c5d8..0x678.
    # Left un-rebased they point into the port's reserved DS main RAM, which
    # is mapped and ZEROED, so OAM::Render's list walk never meets the
    # 0xffff terminator and runs the full 2.9 MB to 0x02400000 -- one byte
    # past the region -- and takes the process with it.
    #
    # So scan back over every candidate that could still reach v and take the
    # SMALLEST one that does. Smallest is the most specific: a named symbol
    # beats the gap block that happens to span it, which is what the DS's own
    # flat memory would have given.
    def covering(v):
        best = None
        i = bisect.bisect_right(starts, v) - 1
        while i >= 0 and v - ivals[i][0] <= widest:
            s, e, n = ivals[i]
            if s <= v < e and (best is None or e - s < best[1] - best[0]):
                best = ivals[i]
            i -= 1
        return best

    patches = []
    for name, a, size, blob in emitted:
        for off in range(0, size - 3, 4):
            v = int.from_bytes(blob[off:off + 4], "little")
            hit = covering(v)
            if hit is not None:
                patches.append("    *(unsigned int *)(%s + %d) = "
                               "(unsigned int)(%s + %d);"
                               % (name, off, hit[2], v - hit[0]))
    lines.append("")
    lines.append("void port_%s_%spatch(void)\n{"
                 % (ov, "syms_" if pack else ""))
    lines.extend(patches)
    lines.append("}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"{len(wanted)} symbols, {len(patches)} pointer patches -> {out_path}")


if __name__ == "__main__":
    main()
