#!/usr/bin/env python3
"""Emit overlay data symbols as C arrays, bytes from the overlay image.

The Player (and every overlay actor) reads static tables baked into its
overlay's data section: animation-file entries, state objects, tuning
constants. Host symbols need that content, so this reads the overlay
binary plus its symbols.txt (sizes = next-symbol deltas) and emits real
bytes for a requested symbol list. Never committed: Nintendo bytes stay
out of git, same policy as romdata.py.

DS-code POINTERS inside emitted data (state Init/Main/Cleanup slots and
the like) are meaningless on host; callers patch those fields at runtime
with host addresses -- see the gate-10 smoke.

    python tools/ovdata.py <ovNNN> <out.c> <symbol> [symbol...]
    python tools/ovdata.py ov002 out.c --from-list syms.txt
"""

import pathlib
import re
import struct
import sys


def main():
    root = pathlib.Path(__file__).resolve().parents[2]
    ov = sys.argv[1]
    out_path = pathlib.Path(sys.argv[2])
    if sys.argv[3] == "--from-list":
        wanted = list(dict.fromkeys(pathlib.Path(sys.argv[4]).read_text().split()))
    else:
        wanted = sys.argv[3:]

    img = root / f"extracted/dsd/arm9_overlays/{ov}.bin"
    data = img.read_bytes()
    ytxt = (root / "extracted/dsd/arm9_overlays/overlays.yaml").read_text()
    ovid = int(ov[2:])
    m = re.search(rf"id: {ovid}\b.*?base_address: (\d+)", ytxt, re.S)
    base = int(m.group(1))

    # every symbol in the overlay, sorted by address, for size deltas
    syms = []
    for line in (root / f"config/arm9/overlays/{ov}/symbols.txt").read_text().splitlines():
        mm = re.search(r"^(\S+)\s+kind:\S+\s+addr:0x([0-9a-fA-F]+)", line)
        if mm:
            syms.append((int(mm.group(2), 16), mm.group(1)))
    syms.sort()
    addr_of = {n: a for a, n in syms}

    lines = [f"/* GENERATED by port/tools/ovdata.py from {ov}.bin -- local only. */",
             "typedef unsigned char u8;", ""]
    for name in wanted:
        if name not in addr_of:
            sys.exit(f"{name} not in {ov} symbols")
        a = addr_of[name]
        nxt = next((s for s, _ in syms if s > a), a + 4)
        size = max(4, nxt - a)
        off = a - base
        blob = data[off:off + size]
        if len(blob) < size:
            blob = blob + b"\0" * (size - len(blob))   # tail runs into bss
        body = ",".join(str(b) for b in blob)
        lines.append(f"u8 {name}[{size}] = {{ {body} }};")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"{len(wanted)} symbols -> {out_path}")


if __name__ == "__main__":
    main()
