#!/usr/bin/env python3
"""Emit the ROM data constants the gate-4b slice references.

These are read-only tables in the arm9 image (sine table, identity matrices,
texture-matrix constants). They are Nintendo's bytes, so they are never
committed: this reads the local decompressed arm9 (extracted/arm9_dec.bin,
flat image based at 0x02000000) and writes a C file under the build tree.
"""

import pathlib
import struct
import sys

# extracted/arm9_dec.bin: the DECOMPRESSED arm9, flat at base 0x02004000
# (verified by two code anchors: Copy36Bytes @0x0205a548, DecompressLZ16
# @0x0205a754). extracted/dsd/arm9/arm9.bin is the COMPRESSED payload
# (arm9.yaml: compressed true) and must not be read directly. Addresses at
# or past bss_start are runtime-initialized and belong in the HAL.
BASE = 0x02004000
BSS_START = 0x02094640

# (symbol address, byte length, C element type). BSS addresses do not belong
# here -- they are runtime-initialized and live in the HAL as storage.
TABLES = [
    (0x02082128, 48, "int"),        # Model ctor default Matrix4x3
    (0x02082190, 48, "int"),        # matrix Render uses for a NULL argument
    (0x02082214, 0x4000, "short"),  # s16 trig table the material bind indexes
    (0x020755A0, 12, "char"),       # OBJ width table (shape x size)
    (0x020755AC, 12, "char"),       # OBJ height table
]


# Initialized arm9 data referenced by name: address + size resolve from
# config/arm9/symbols.txt (size = delta to the next symbol, the ovdata.py
# convention). Emitted as aligned byte arrays so any struct view works.
NAMED = [
    "data_0208a178", "data_0208c178",
    "data_0208e504", "data_0208e538", "data_0208e548", "data_0208e54c",
    "data_0208e55c", "data_0208e56c", "data_0208e57c", "data_0208e58c",
    "data_0208e59c", "data_0208e5b0", "data_0208e5c0", "data_0208e5d4",
    "data_0208e5e4", "data_0208e5f0", "data_0208e5fc", "data_0208e608",
    "data_0208e610", "data_0208e624", "data_0208e634", "data_0208e648",
    "data_02092120",
    "data_02082178", "data_02090e80", "data_020914a0",
    "data_02092584", "data_02092654", "data_02092668", "data_0208e500", "data_02086758", "data_02086a58", "data_0208e430", "data_02086b58",
    "data_0208e434", "data_0208e438", "data_0208e43c", "data_0208e440",
    "data_0208e444", "data_02092124", "data_02086384", "data_0208e448", "data_02086bc0", "data_02086bd8", "data_02086c20", "data_02086c38", "data_02086c50", "data_02086c60", "data_02086c78", "data_02086c80", "data_02086c88", "data_02086c90", "data_02086ca0", "data_02086ca8", "data_02086cb0", "data_02086cb8", "data_02086cc0", "data_02086cd0", "data_02086cd8", "data_02086ce8", "data_02086cf0", "data_02086cf8", "data_02086d00", "data_02086d08", "data_02086d18", "data_02086d20", "data_02086d38", "data_02086d40", "data_02086d60", "data_02086d68", "data_02086d80", "data_02086d88", "data_02086d98", "data_02086da0", "data_02086dc0", "data_02086dd8", "data_02086df0", "data_02086e08", "data_02086e20", "data_02086e30", "data_02086e38", "data_02088fb8", "data_020890a0", "data_02092118", "data_02092110", "data_020876e4", "data_0208eecc", "data_02092134",
    "data_0208e42c",
    "data_0208ee44",
    "data_0208ee8c",
    "data_0208eeac",
    "data_0208f074",
    "data_0208f174",
    "data_020756b0",   # D-pad direction -> binang table (Stage::CheckInput)
    "data_0209214c",   # per-mode button remap pointer table (CheckInput)
    "data_02086fcc",   # func_0200cb58 table (state-family ring)
]


def named_entries(root):
    import re
    syms = []
    for line in (root / "config/arm9/symbols.txt").read_text().splitlines():
        m = re.search(r"^(\S+)\s+kind:\S+\s+addr:0x([0-9a-fA-F]+)", line)
        if m:
            syms.append((int(m.group(2), 16), m.group(1)))
    syms.sort()
    addr_of = {n: a for a, n in syms}
    out = []
    for name in NAMED:
        a = addr_of[name]
        nxt = next((s for s, _ in syms if s > a), a + 4)
        out.append((name, a, max(4, nxt - a)))
    return out


def main():
    root = pathlib.Path(__file__).resolve().parents[2]
    img = root / "extracted/arm9_dec.bin"
    if not img.exists():
        sys.exit(f"missing {img} -- extract the ROM first")
    anchor = img.read_bytes()
    a = 0x0205A548 - BASE
    if anchor[a:a + 4] != b"\x0c\x10\xb0\xe8":
        sys.exit("arm9_dec.bin failed the Copy36Bytes anchor -- wrong image/base")
    for addr, length, _ in TABLES:
        if addr + length > BSS_START:
            sys.exit(f"{addr:#x}+{length:#x} crosses into BSS -- not file-backed")
    data = img.read_bytes()
    out_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else (
        root / "build/port/host-src/romdata.c")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = ["/* GENERATED by port/tools/romdata.py from extracted/arm9_dec.bin.",
             " * ROM constants stay out of git; regenerate locally. */", ""]
    for addr, length, ctype in TABLES:
        off = addr - BASE
        blob = data[off:off + length]
        if len(blob) != length:
            sys.exit(f"short read at {addr:#x}")
        width = 4 if ctype == "int" else 2
        fmt = "<i" if ctype == "int" else "<h"
        vals = [struct.unpack_from(fmt, blob, i)[0] for i in range(0, length, width)]
        name = f"data_{addr:08x}"
        body = ", ".join(str(v) for v in vals)
        lines.append(f"{ctype} {name}[{len(vals)}] = {{ {body} }};")
        lines.append("")
    for name, addr, size in named_entries(root):
        if addr + size > BSS_START:
            size = BSS_START - addr
        blob = data[addr - BASE:addr - BASE + size]
        body = ",".join(str(b) for b in blob)
        lines.append(f"__declspec(align(8)) unsigned char {name}[{size}] = "
                     f"{{ {body} }};")
    lines.append("")

    # The archive-mount table at data_0208ecf4: 13 entries of
    # {ptr, heap, u16 idBase, u16 idEnd, char *shortName, char *narcPath}.
    # Interior file IDs (>= 0x8000) resolve as narc[id - idBase]; the fs
    # seam consumes this host-shaped copy (see port/hal/fs.cpp).
    lines.append("struct port_arc_entry { unsigned short base, end;"
                 " const char *narc; };")
    ents = []
    off = 0x0208ECF4 - BASE
    for i in range(13):
        blob = data[off + i*0x14: off + (i+1)*0x14]
        base_id, end_id = struct.unpack_from("<HH", blob, 8)
        path_ptr = struct.unpack_from("<I", blob, 0x10)[0]
        p = data[path_ptr - BASE:path_ptr - BASE + 64].split(b"\0")[0]
        ents.append('    { %d, %d, "%s" },' % (base_id, end_id,
                                               p.decode("ascii").lstrip("/")))
    lines.append("struct port_arc_entry port_archive_map[13] = {")
    lines.extend(ents)
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="ascii")
    print(f"romdata -> {out_path}")


if __name__ == "__main__":
    main()
